Exit code: 1
---
Stdout:
======================= Schemathesis test session starts =======================
Schema location: http://127.0.0.1/schema.yaml
Base URL: http://127.0.0.1/api
Specification version: Open API 3.0.2
Random seed: 42
Workers: 1
Collected API operations: 1
Collected API links: 0
API probing: SUCCESS
Schema analysis: SKIP

POST /api/payload E                                                       [100%]

==================================== ERRORS ====================================
______________________________ POST /api/payload _______________________________
Runtime Error

Something bad happen

    Traceback (most recent call last):
      File "/package-root/runner/phases/unit/_executor.py", line XXX, in wrapped
        f(ctx=ctx, case=case, result=result, **kwargs)
      File "/package-root/runner/phases/unit/_executor.py", line XXX, in test_func
        targets.run(ctx.config.execution.targets, case=case, response=response)
      File "/package-root/generation/targets.py", line XXX, in run
        value = target(context)
      File "/tmp/module.py", line XXX, in buggy
        raise AssertionError("Something bad happen")
    AssertionError: Something bad happen

Need more help?
    Join our Discord server: https://discord.gg/R9ASRAmHnA
=================================== SUMMARY ====================================

No checks were performed.

Tip: Use the `--report` CLI option to visualize test results via Schemathesis.io.
We run additional conformance checks on reports from public repos.

============================== in 1.00s ========================================
